#!/bin/bash

cd ..
###

mkdir Windows

#Genom in Gleichgrosse Stücke portionieren mit bedtools.
#bedtools makewindows -g ./MpTak1v5_chrom.txt -w 200 > ./Windows/MpTak1v5_200bpwindows.bed
bedtools makewindows -g ./P*chrom.txt -w 200 > ./Windows/Physcomitriumpatens_200bpwindows.bed

#Dann kann man noch einen bed file machen, in dem dann für jedes Fenser die Anzahl der hits steht. Kann man auch so sortieren, dass die fenster mit den höchsten hits am Anfang des files stehen.

#bedtools coverage -a ./Windows/MpTak1v5_200bpwindows.bed -b ./BED-files/telobox_Mp*.bed -counts|  sort -k1,1 -k2,2n >./Windows/MpTak1v5_counts_hitsperwindow.bed
bedtools coverage -a ./Windows/Physcomitriumpatens_200bpwindows.bed -b ./BED-files/telobox_P*.bed -counts|  sort -k1,1 -k2,2n > ./Windows/Physcomitriumpatens_counts_hitsperwindow.bed




#bedtools intersect -a ./Windows/MpTak1v5_200bpwindows.bed -b ./BED-files/telobox_Mp*.bed -v |  sort -k1,1 -k2,2n >./Windows/MpTak1v5_intersect_hitsperwindow.bed
bedtools intersect -a ./Windows/Physcomitriumpatens_200bpwindows.bed -b ./BED-files/telobox_P*.bed -v|  sort -k1,1 -k2,2n > ./Windows/Physcomitriumpatens_intersect_hitsperwindow.bed



####
#Genom in Gleichgrosse Stücke portionieren mit bedtools. Beispiel war mit einer A. thaliana Ref, aber help menue oder manual gibt die Optionen aus. Ergebnis: Bedfile mit Fenstern 
#bedtools makewindows -g /common/TAIR10/TAIR10.chrlength.txt -w 200 > TAIR10_200bpwindows.bed
#Dann kann man noch einen bed file machen, in dem dann für jedes Fenser die Anzahl der hits steht. Kann man auch so xsortieren, dass die fenster mit den höchsten hits am Anfang des files stehen.
#bedtools coverage -a Fuzznucfile.bed -b  TAIR10_200bpwindows.bed |  sort -k1,1 -k2,2n >neuer_file.bed
#Möglich wäre auch ein Histogram um zu sehen wie die Verteilung so ist, die meisten Fenster sollten ja 0 oder max 1 hit haben. Solche Sachen würde ich in R plotten. Wieviel hast Du damit schon gearbeitet?
#Es gibt auch eine Funktion bedtools getfasta mit der man sich einen multiplen FASTA file mit dem top der Tabelle holen kann, um scaffolds oder chormosomen positionen zu finden, die unnatürlich viele teloboxen haben, 
#als viellicht interstitial telomere oder echte telomere anzeigen. Beim Matrix-rechnen in den deeptools kann man die sich dann übrigens in eine blacklist packen, damit die von den Berechnungen verschwinden.

####
 