#!/bin/bash

#create bwa index for MARCHANTIA. Needs to be done only once

mkdir BWA-align
mkdir BWA-align/BAM-files
mkdir BWA-align/BED-files


cd /netscratch/dep_coupland/grp_turck/carina/Downloads/
bwa index -p MpTak1v5.1bwaidx -a bwtsw MpTak1v5.1.fasta

#alingn with standard parameters

#there are now problems with different version of bwa and samtools. Try to fix this by using bwa mem instead of bwa aln as previously. The output is a sam file


cd /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/fastq

######TEST

#declare -a file1
#declare -a file2

#file1=(SRR9974612_1.fastq )
#file2=(SRR9974612_2.fastq)
#n=${#file1}
#for ((i=0;i<$n;i++)); do
#do
#bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx ${file1[$i]} ${file2[$i]} | samtools view -b - | samtools sort - -o "${i%.fastq}.bam"
#done


#for i in SRR997461
#do
#bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx $i_1fastq $i_2fastq | samtools view -b - | samtools sort - -o "${i%.fastq}.bam"
#done

##########


bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx SRR9974612_1.fastq SRR9974612_2.fastq | samtools view -b - | samtools sort - -o SRR9974612.bam
bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx SRR9974623_1.fastq SRR9974623_2.fastq | samtools view -b - | samtools sort - -o SRR9974623.bam
bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx SRR9974624_1.fastq SRR9974624_2.fastq | samtools view -b - | samtools sort - -o SRR9974624.bam
bwa mem -t 4 /netscratch/dep_coupland/grp_turck/carina/Downloads/MpTak1v5.1bwaidx SRR9974632_1.fastq SRR9974632_2.fastq | samtools view -b - | samtools sort - -o SRR9974632.bam


#make bedfiles from the bam files
for i in *bam
do 
bedtools bamtobed -i $i > "${i%.bam}.bed"
done 


#count the mapped reads for each mapping
for i in *bed
do
wc -l $i >>mapped_reads.txt
done

mv *.bam ../BWA-align/BAM-files
mv *.bed ../BWA-align/BED-files

cd -

 
 #cd ..
 #cd ..
 ## There was also a filtering for clonal reads while doing SICER
 #cd BWA-align/BED-files/SICER_Output
 #for i in *1-removed*
 #do
 #wc -l $i >> ../../mapped_reads.txt
 #done
 #cd ..
 #cd ..
 #cd ..
 
# bsub -q normal -R 10240 -M 12288 sh 2_BWAalign.sh

 