#!/bin/bash

#export PATH=/netscratch/dep_coupland/grp_turck/lib/miniconda/bin/


#SRR9974612: H3K27me3_Tak1_rep3
#SRR9974623: H3K27me3_Tak1_rep2
#SRR9974624:  H3K27me3_Tak1_rep1
#SRR9974632: H3_Tak1_rep1

mkdir EPIC
cd ./BWA-align/BAM-files

#epic2 --treatment BAMFILE -control BAMfile -cs $HOME/chrom  --bin-size 100 --fragment-size 300 --output test


#rep1
epic2 --treatment *24.bam --control *32.bam --chromsizes /netscratch/dep_coupland/grp_turck/carina/MpTak1v5_chrom.txt --bin-size 100 --fragment-size 300 --output /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/EPIC/testrep1

#rep2
epic2 --treatment *23.bam --control *32.bam --chromsizes /netscratch/dep_coupland/grp_turck/carina/MpTak1v5_chrom.txt --bin-size 100 --fragment-size 300 --output /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/EPIC/testrep2

#rep3
epic2 --treatment *12.bam --control *32.bam --chromsizes /netscratch/dep_coupland/grp_turck/carina/MpTak1v5_chrom.txt --bin-size 100 --fragment-size 300 --output /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/EPIC/testrep3

#bedtools shuffle: Kontrolle erstellen 
bedtools shuffle -i /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/EPIC/testrep1 -g /netscratch/dep_coupland/grp_turck/carina/MpTak1v5_chrom.txt > /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/EPIC/controlrep1

