#!/bin/bash

cd ..

###Convert gff file to bed file

convert2bed --input=gff <./Downloads/Marchantia_polymorpha_subsp._polymorpha_annos1-cds0-id_typename-nu1-upa1-add_chr0.gid55051.gff >./Annotation_Files/gff2bed_Marchantia.bed

convert2bed --input=gff <./Downloads/Physcomitrium_patens_formerly_Physcomitrella_patens_annos1-cds0-id_typename-nu1-upa1-add_chr0.gid33928.gff >./Annotation_Files/gff2bed_Physcomitrium_patens.bed

convert2bed --input=gff <./Downloads/MpTak1v5.1_r1.gff >./Annotation_Files/gff2bed_MpTak1v5.1.bed
