#!/bin/bash

cd ../BIGWIG

#### Sort Bigwig by converting it into BED file format, then sorting it and reconverting it to Bigwig

bigWigToBedGraph telobox_Physcomitrium_patensblacklist.bw telobox_Physcomitrium_patens_BWtoBED.bed
sort -k1,1 -k2,2n telobox_Physcomitrium_patens_BWtoBED.bed > sorted_telobox_Physcomitrium_patens_BWtoBED.bed
bedGraphToBigWig sorted_telobox_Physcomitrium_patens_BWtoBED.bed ../Physcomitrium_patens_chrom.txt sorted_telobox_Physcomitrium_patens_blacklist.bw

#bigWigToBedGraph telobox_MpTak1v5.1blacklist.bw telobox_MpTak1v5.1_BWtoBED.bed
#sort -k1,1 -k2,2n telobox_MpTak1v5.1_BWtoBED.bed > sorted_telobox_MpTak1v5.1_BWtoBED.bed
#bedGraphToBigWig sorted_telobox_MpTak1v5.1_BWtoBED.bed ../MpTak1v5_chrom.txt sorted_telobox_MpTak1v5.1blacklist.bw

#bigWigToBedGraph telolike_M*blacklist.bw telolike_Mp_BWtoBED.bed 
#sort -k1,1 -k2,2n telolike_Mp_BWtoBED.bed > sorted_telolike_MpTak_BWtoBED.bed
#bedGraphToBigWig sorted_telolike_MpTak_BWtoBED.bed ../MpTak1v5_chrom.txt sorted_telolike_MpTakblacklist.bw

bigWigToBedGraph telolike_P*blacklist.bw telolike_Physcomitrium_BWtoBED.bed
sort -k1,1 -k2,2n telolike_Physcomitrium_BWtoBED.bed > sorted_telolike_Physcomitrium_patens_BWtoBED.bed
bedGraphToBigWig sorted_telolike_Physcomitrium_patens_BWtoBED.bed ../Physcomitrium_patens_chrom.txt sorted_telolike_Physcomitrium_patens_blacklist.bw


rm *bed