#!/bin/bash

cd Heatmaps



for i in *CUS1.bed
do
awk '$13 == "cluster_1" {print$4}' /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/Heatmaps/telolike*.bed >> /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/GO-Analyse/"${i%.bed}_cluster1.txt"
awk '$13 == "cluster_2" {print$4}' /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/Heatmaps/telolike*.bed >> /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/GO-Analyse/"${i%.bed}_cluster2.txt"
awk '$13 == "cluster_3" {print$4}' /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/Heatmaps/telolike*.bed >> /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/GO-Analyse/"${i%.bed}_cluster3.txt"
awk '$13 == "cluster_4" {print$4}' /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/Heatmaps/telolike*.bed >> /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/GO-Analyse/"${i%.bed}_cluster4.txt"
done 

#cd /netscratch/dep_coupland/grp_turck/carina/Downloads/Marchantia-chromatin/GO-Analyse


#for b in *.bed
#do
#sed -i '/Before/d' $b
#awk -i inplace '{sub(/^\S+\s*/,"")}1' $b
#cut -d\. -f1 $b >> $b.converted.txt
#done


###for TOP-GO

#awk '{a[$1]=a[$1]" " $2}END{for (i in a) print i"\t" a[i]}' MpTak1v5.1r1_GO_annotation.tsv >> GO-Annotation.map

###manually remove space between GO and genes, add comma between genes in Notepad++



###for ViSEAGO
 
#awk {'print $1'} MpTak1v5.1r1_GO_annotation.tsv >> Gene-file.txt
#pr -m -t --header="taxid	gene_id	gene_symbol	GOID	evidence"    Gene-file.txt MpTak1v5.1r1_GO_annotation.tsv | gawk '{print "Marchantia_polymorpha",$1,$2,$3, "CG" }' >> GO-Annotation.txt
